### ISSUE TITLE
Output from STDOUT is sometimes incomplete

### ISSUE THREAD

**Issue by rexissimus** [remram44/tej#12]
In vistrails, connect a `Queue` to a `PythonSource` with the following contents:

    print queue._call("printf 'ABCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCC%.0s\n' {1..40} | tail -n 40", True)[1]

When executed, sometimes not all output is printed. It seems like the collection of output from `tail` is interrupted for some reason.

**Comment by remram44** [comment]
Yes, I see the problem in the code, will fix shortly. `_call()` should never actually return enough data to trigger this though, output is always written to files...
